apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: app
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80;
          server_name  localhost;
          access_log /var/log/nginx/example.journaldev.com-access.log;
          error_log  /var/log/nginx/example.journaldev.com-error.log error;
          location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
      }
    }

